apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockets
  labels:
    app: websockets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websockets
  template:
    metadata:
      labels:
        app: websockets
    spec:
      containers:
        - name: user
          image: sachingoyaldocker/baat-org-websockets:1.0
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: RABBITMQ_HOST
              value: "chat-mq"
            - name: USER_SERVICE_URI
              value: "http://user:8080"
          ports:
            - containerPort: 8080
          imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: websockets
  labels:
    app: websockets
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: websockets
  type: LoadBalancer
