apiVersion: v1
kind: Service
metadata:
  name: chat-mq
spec:
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app: chat-mq
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-mq
  name: chat-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-mq
  template:
    metadata:
      labels:
        app: chat-mq
    spec:
      containers:
        - image: rabbitmq:management
          name: chat-mq
          ports:
            - containerPort: 15671
            - containerPort: 5671
