apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: sachingoyaldocker/baat-org-user:1.0
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_HOST
              value: "user-db"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "user"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_INITIALISE
              value: "true"
          ports:
            - containerPort: 8080
