apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: sachingoyaldocker/baat-org-user
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_HOST
              value: "user-db"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "user"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_INITIALIZATION_MODE
              value: "always"
          ports:
            - containerPort: 8080
          imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: user
  type: LoadBalancer
